[package]
name = "rocket-cli"
version = "0.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
colored = "3.0.0"
crossterm = "0.29.0"
handlebars = { version = "6.3.2", features = ["dir_source"] }
log = "0.4.27"